# Simple Application Context Demo

This project contains a simple piece of Around
advice.

## Classes In The Project

[source,java]
.src/main/java/contextdemo/PrintlnTraceInterceptor.java
----
package contextdemo;

import io.micronaut.aop.MethodInterceptor;
import io.micronaut.aop.MethodInvocationContext;

import javax.inject.Singleton;

@Singleton
public class PrintlnTraceInterceptor implements MethodInterceptor {
    @Override
    public Object intercept(MethodInvocationContext context) {
        System.out.println("Invoking method " + context.getExecutableMethod().getMethodName() + " on class " + context.getDeclaringType());
        return context.proceed();
    }
}
----

The `PrintlnTrace` annotation is associated with that advice.

[source,java]
.src/main/java/contextdemo/PrintlnTrace.java
----
package contextdemo;

import io.micronaut.aop.Around;
import io.micronaut.context.annotation.Type;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Documented
@Retention(RUNTIME)
@Target({ElementType.METHOD})
@Around
@Type(PrintlnTraceInterceptor.class)
public @interface PrintlnTrace {
}
----

A trivial `Singleton` bean has that advice applied to it.

[source,java]
.src/main/java/contextdemo/SomeHelper.java
----
package contextdemo;

import javax.inject.Singleton;

@Singleton
public class SomeHelper {
    @PrintlnTrace
    public void doSomething() {
        System.out.println("Hello From SomeHelper");
    }
}
----

The `Application` class creates an `ApplicationContext`, retrieves
the `SomeHelper` bean from the context and interacts with it.

[source,java]
.src/main/java/contextdemo/Application.java
----
package contextdemo;

import io.micronaut.context.ApplicationContext;

public class Application {

    public static void main(String[] args) {
        final ApplicationContext context = ApplicationContext.run();
        final SomeHelper helper = context.getBean(SomeHelper.class);
        helper.doSomething();
    }
}
----

## Run The Application

The application may be run with Gradle.

    ./gradlew run

An executable .jar may be created.

    ./gradlew shadowJar
    java -jar build/libs/micronaut-context-demo-0.1-all.jar

The output indicates that the bean exists in the application
context and that the expected advice is applied to that bean.

```
$ ./gradlew run

> Task :run
Invoking method doSomething on class class contextdemo.SomeHelper
Hello From SomeHelper

BUILD SUCCESSFUL in 1s
```

```
$ ./gradlew shadowJar

> Task :compileJava

BUILD SUCCESSFUL in 1s
2 actionable tasks: 2 executed

$ java -jar build/libs/micronaut-context-demo-0.1-all.jar
Invoking method doSomething on class class contextdemo.SomeHelper
Hello From SomeHelper
```


